services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: healthsync
      POSTGRES_USER: healthsync
      POSTGRES_PASSWORD: healthsyncpass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  db_data:
